Passwords = [
    "MomMOm22",
    "JesusMyWay2012",
    "HArderDAdd6969",
    "YOURmomhaha",
    "Bitchyanme78",
    "CringeLord96",
    "ANIMEloveee88",
]


email = [
    "bronopls@gmail.com",
    "fatalistisk@devoc.site",
    "terentmarina@fangeradelman.com",
    "raquel83@gmailya.com",
    "einwan@greendike.com",
    "seemly@isluntvia.com",
    "donikavadim@shopduylogic.vn",
    "verdbeal@suttal.com",
    "erangad@yandex.cfd",
    "kathry1@usbvap.com",
    "aurelani@gamakang.com",
    "lisbnjvi@gotcertify.com",
    "antbanks@gagokaba.com",
    "seka97@makente.com",
    "diagocha@hmpoeao.com",
]


words = [
    "soup",
    "mount",
    "extend",
    "brown",
    "bruh",
    "mk",
    "dildo",
    "kiss",
    "crust",
    "backpack",
    "josis",
    "dead",
    "lol",
    "lmao",
    "lmfao",
    "mint",
    "coat",
    "pedo",
    "match",
    "excite",
    "hmph",
    "oink",
    "dad",
    "sis",
    "foreman",
    "simp",
    "optimal",
    "wick",
    "gay",
    "man",
    "coral",
    "chill",
    "token",
    "hack",
    "mom",
    "condom",
    "asthma",
    "rage",
    "rabbit",
    "whisper",
    "lady",
    "donkey",
    "zoo",
    "nigeria",
    "wise",
    "race",
    "snow",
    "slave",
    "deny",
    "polarity",
    "pee",
    "hook",
    "ew",
    "fine",
]


ip = [
    "12.789.4508",
    "17.345.5678",
    "96.098.6789",
    "23.253.2767",
    "76.907.9988",
    "23.499.0098",
    "12.221.2009",
    "123.555.6876",
    "32.765.4567",
    "432.67.677",
    "76.8.777",
    "87.788.7888",
    "69.690.6969",
    "24.009.6969",
    "62.444.5555",
]


nick = [
    "Johnny",
    "Snakes Snuggleshine",
    "Rock Candy Wigglesworth",
    "Schlomo Sugar-Gold",
    "Bill Beenie-Weenie Jenkins",
    "TeeTee Endicott",
    "Cinnabuns Oxhandler",
    "Elphonso Olivetti",
    "Sweet Tea Weiners",
    "Lil Debil Goodensmith",
    "Chad Fewhairs",
    "Sid The Squirts Goodensmith",
    "Soupcan Sam Bigmeat",
    "Lemongrass Rosenthal",
    "Spitzitout Snuggleshine",
    "Jimbo Goodensmith",
    "Ignatious Rubbins",
    "Gootsy Cocktoasten",
    "Lunch Money Nettles",
    "Bud 'Lite' Henderson",
    "Spitzitout Winterkorn",
    "Boxelder Clovenhoof",
    "Potato Bug Pennywhistle",
    "Butterbean Rosenthal",
    "Cinnabuns Kingfish",
    "Chigger Listenbee",
    "Old Scratch Jenkins",
]


status = [
    "He had accidentally hacked into his company's server.",
    "It isn't true that my mattress is made of cotton candy.",
    "If I don’t like something, I’ll stay away from it.",
    "Mary plays the piano.",
    "There is no better feeling than staring at a wall with closed eyes.",
    "My but is sweating",
    "He found rain fascinating yet unpleasant.",
    "Instead of a bachelorette party",
    "Please tell me you don't work in a morgue.",
    "BTS",
    "People keep telling me orange but I still prefer pink",
    "I caught my squirrel rustling through my gym bag.",
    "He colored deep space a soft yellow.",
    "Bill ran from the giraffe toward the dolphin.",
    "I'm not a party animal, but I do like animal parties.",
    "I trust everything that's written in purple ink.",
    "Carol drank the blood as if she were a vampire.",
    "He drank life before spitting it out.",
    "The paintbrush was angry at the color the artist chose to use.",
    "I ate a sock because people on the Internet told me to.",
]


insults = [
    "SLUTTY CR0TCH HAMMER",
    "SLUTTY PR*CK TOOLBAG",
    "WH1TE TRASH TAINT KNOB",
    "POMPOUS SLVT MONSTER",
    "PIE-EATING NUT WAFFLE",
    "ID1OTIC PR*CK PIRATE",
    "SLUTTY SH*T PIRATE",
    "TONE DEAF C0CK WAFFLE",
    "TONE DEAF NUT TOOLBAG",
    "C0MMUN1ST DUCK DRAGON",
    "INSECURE SHART BOX",
    "DUCKN0SE SHART KNOB",
    "POMPOUS SHART GOBLIN",
    "SLIMY C0CK WAFFLE",
    "EL1TIST CR0TCH MONSTER",
    "DUCKN0SE DOUCHE DRAGON",
    "PIE-EATING NUT PILOT",
    "STUPID BUTT TOOLBAG",
    "PIE-EATING TAINT KNOB",
    "LAZY CR0TCH BISCUIT",
]
